[package]
name = "squish"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.26", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

confy = "0.5"
dialoguer = "0.10.3"
